trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '09bdde2f-d919-4dfe-a292-a140c5a96b43'

  # Web app name
  webAppName: 'PipelineApps'

  # Environment name
  environmentName: 'PipelineApps'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- template: templates/build.yml
- template: templates/deploy.yml