stages:
- stage: 'Deploy'
    displayName: 'Deploy the web app'
    dependsOn: Build
    jobs:
      - job: deployJob
        steps:
              - task: AzureWebApp@1
                displayName: 'Azure app service deploy'
                inputs:
                  azureSubscription: 'Azure subscription 1 (f016713d-47fd-4917-a2c7-c2805377c59c)'
                  appName: '$(WebAppName)'
                  appType: 'webAppLinux'
                  package: '$(Build.ArtifactStagingDirectory)'  
